import type { EnterpriseModuleName } from '../interfaces/iModule';

export const ENTERPRISE_MODULE_NAMES: Record<EnterpriseModuleName, 1> = {
    AdvancedFilterModule: 1,
    AllEnterpriseModule: 1,
    CellSelectionModule: 1,
    ClipboardModule: 1,
    ColumnMenuModule: 1,
    ColumnsToolPanelModule: 1,
    ContextMenuModule: 1,
    ExcelExportModule: 1,
    FiltersToolPanelModule: 1,
    GridChartsModule: 1,
    IntegratedChartsModule: 1,
    GroupFilterModule: 1,
    MasterDetailModule: 1,
    MenuModule: 1,
    MultiFilterModule: 1,
    PivotModule: 1,
    RangeSelectionModule: 1,
    RichSelectModule: 1,
    RowGroupingModule: 1,
    RowGroupingPanelModule: 1,
    ServerSideRowModelApiModule: 1,
    ServerSideRowModelModule: 1,
    SetFilterModule: 1,
    SideBarModule: 1,
    SparklinesModule: 1,
    StatusBarModule: 1,
    TreeDataModule: 1,
    ViewportRowModelModule: 1,
};
