import type { UserComponentName } from '../../context/context';
import type { ModuleName } from '../../interfaces/iModule';

export const USER_COMP_MODULES: Record<UserComponentName, ModuleName> = {
    agSetColumnFilter: 'SetFilterModule',
    agSetColumnFloatingFilter: 'SetFilterModule',
    agMultiColumnFilter: 'MultiFilterModule',
    agMultiColumnFloatingFilter: 'MultiFilterModule',
    agGroupColumnFilter: 'GroupFilterModule',
    agGroupColumnFloatingFilter: 'GroupFilterModule',
    agGroupCellRenderer: 'GroupCellRendererModule',
    agGroupRowRenderer: 'GroupCellRendererModule',
    agRichSelect: 'RichSelectModule',
    agRichSelectCellEditor: 'RichSelectModule',
    agDetailCellRenderer: 'SharedMasterDetailModule',
    agSparklineCellRenderer: 'SparklinesModule',
    agDragAndDropImage: 'SharedDragAndDropModule',
    agColumnHeader: 'ColumnHeaderCompModule',
    agColumnGroupHeader: 'ColumnGroupHeaderCompModule',
    agSortIndicator: 'SortModule',
    agAnimateShowChangeCellRenderer: 'HighlightChangesModule',
    agAnimateSlideCellRenderer: 'HighlightChangesModule',
    agLoadingCellRenderer: 'LoadingCellRendererModule',
    agSkeletonCellRenderer: 'SkeletonCellRendererModule',
    agCheckboxCellRenderer: 'CheckboxCellRendererModule',
    agLoadingOverlay: 'LoadingOverlayModule',
    agNoRowsOverlay: 'NoRowsOverlayModule',
    agTooltipComponent: 'TooltipModule',
    agReadOnlyFloatingFilter: 'CustomFilterModule',
    agTextColumnFilter: 'TextFilterModule',
    agNumberColumnFilter: 'NumberFilterModule',
    agDateColumnFilter: 'DateFilterModule',
    agDateInput: 'DateFilterModule',
    agTextColumnFloatingFilter: 'TextFilterModule',
    agNumberColumnFloatingFilter: 'NumberFilterModule',
    agDateColumnFloatingFilter: 'DateFilterModule',
    agCellEditor: 'TextEditorModule',
    agSelectCellEditor: 'SelectEditorModule',
    agTextCellEditor: 'TextEditorModule',
    agNumberCellEditor: 'NumberEditorModule',
    agDateCellEditor: 'DateEditorModule',
    agDateStringCellEditor: 'DateEditorModule',
    agCheckboxCellEditor: 'CheckboxEditorModule',
    agLargeTextCellEditor: 'LargeTextEditorModule',
    agMenuItem: 'MenuItemModule',
    agColumnsToolPanel: 'ColumnsToolPanelModule',
    agFiltersToolPanel: 'FiltersToolPanelModule',
    agAggregationComponent: 'StatusBarModule',
    agSelectedRowCountComponent: 'StatusBarModule',
    agTotalRowCountComponent: 'StatusBarModule',
    agFilteredRowCountComponent: 'StatusBarModule',
    agTotalAndFilteredRowCountComponent: 'StatusBarModule',
};
