import { ModuleName } from 'ag-grid-community';

import { CommunityModuleName, EnterpriseModuleName } from '../../packages/ag-grid-community/src/interfaces/iModule';

export const AllCommunityModules: Record<CommunityModuleName, number> = {
    AlignedGridsModule: 3.06,
    AllCommunityEditorsModule: 51.29,
    AllCommunityModule: 546.49,
    AnimateShowChangeCellRendererModule: 1.73,
    AnimateSlideCellRendererModule: 1.45,
    AnimationFrameModule: 2.21,
    AriaModule: 1.23,
    CellApiModule: 0.28,
    CellFlashModule: 0.98,
    CellRendererFunctionModule: 0.48,
    CellStyleModule: 2.24,
    ChangeDetectionModule: 2.5,
    CheckboxCellRendererModule: 9.79,
    ClientSideRowModelApiModule: 30.21,
    ClientSideRowModelCoreModule: 28.33,
    ClientSideRowModelDefaultModule: 168.33,
    ClientSideRowModelFilterModule: 13.64,
    ClientSideRowModelModule: 521.64,
    ClientSideRowModelSortModule: 41.3,
    ColumnAnimationModule: 1.41,
    ColumnApiModule: 2.53,
    ColumnAutoSizeModule: 10.02,
    ColumnFilterModule: 46.03,
    ColumnFlexModule: 1.81,
    ColumnGroupHeaderCompModule: 2.9,
    ColumnGroupModule: 11.88,
    ColumnHeaderCompModule: 5.18,
    ColumnHoverModule: 1.58,
    ColumnMoveCoreModule: 33.62,
    ColumnMoveModule: 35.07,
    ColumnResizeModule: 14.81,
    CommunityDefaultModule: 139.07,
    CommunityFeaturesModule: 494.89,
    CsvExportModule: 11.3,
    DataTypeEditorsModule: 34.81,
    DataTypeModule: 22.16,
    DefaultEditorModule: 25.82,
    EditCoreModule: 17.71,
    EditModule: 57.76,
    EventApiModule: 2.64,
    ExpressionModule: 0.86,
    FilterCoreModule: 12.34,
    FilterModule: 139.87,
    FloatingFilterModule: 52.65,
    FullRowEditModule: 18.34,
    GetColumnDefsApiModule: 1.76,
    InfiniteRowModelApiModule: 18.16,
    InfiniteRowModelCoreModule: 17.17,
    InfiniteRowModelDefaultModule: 156.31,
    InfiniteRowModelModule: 507.51,
    KeyboardNavigationModule: 20.35,
    LargeTextEditorModule: 24.49,
    LoadingOverlayModule: 7.63,
    LocaleModule: 0.43,
    NativeDragModule: 1.47,
    NoRowsOverlayModule: 7.6,
    OverlayCoreModule: 7.15,
    OverlayModule: 8.06,
    PaginationModule: 37.69,
    PinnedColumnModule: 5.03,
    PinnedRowModule: 9.35,
    QuickFilterModule: 17.07,
    ReadOnlyFloatingFilterModule: 59.59,
    RenderApiModule: 1.48,
    RowApiModule: 0.88,
    RowAutoHeightModule: 1.84,
    RowDragModule: 28.64,
    RowSelectionApiModule: 1.35,
    RowSelectionCoreModule: 35.57,
    RowSelectionModule: 39.32,
    RowStyleModule: 1.24,
    ScrollApiModule: 0.7,
    SelectEditorModule: 36.55,
    SelectionColumnModule: 2.52,
    SimpleFilterModule: 119.47,
    SimpleFloatingFilterModule: 134.77,
    SortCoreModule: 10.28,
    SortIndicatorCompModule: 10.43,
    SortModule: 10.47,
    StateModule: 13.24,
    StickyRowModule: 6.25,
    TooltipCoreModule: 21.77,
    TooltipCompModule: 0.44,
    TooltipModule: 22.24,
    TouchModule: 3.89,
    UndoRedoEditModule: 23.5,
    ValidationModule: 69.56,
    ValueCacheModule: 0.65,
};
export const AllEnterpriseModules: Record<EnterpriseModuleName, number> = {
    AdvancedFilterModule: 253,
    AllEnterpriseModule: 1260,
    CellSelectionCoreModule: 93,
    CellSelectionFillHandleModule: 105,
    CellSelectionModule: 106,
    CellSelectionRangeHandleModule: 97,
    ClientSideRowModelHierarchyModule: 56,
    ClipboardModule: 94,
    ColumnMenuModule: 223,
    ColumnsToolPanelCoreModule: 192,
    ColumnsToolPanelModule: 395,
    ColumnsToolPanelRowGroupingModule: 272,
    ContextMenuModule: 100,
    EnterpriseDefaultModule: 410,
    ExcelExportModule: 113,
    FiltersToolPanelModule: 153,
    GridChartsModule: 144,
    IntegratedChartsModule: 432,
    GroupCellRendererModule: 58,
    GroupFilterModule: 168,
    GroupFloatingFilterModule: 179,
    LoadingCellRendererModule: 47,
    MasterDetailCoreModule: 98,
    MasterDetailModule: 104,
    MenuModule: 229,
    MultiFilterCoreModule: 148,
    MultiFilterModule: 158,
    MultiFloatingFilterModule: 158,
    PivotCoreModule: 123,
    PivotModule: 260,
    RangeSelectionModule: 106,
    RichSelectModule: 111,
    RowGroupingCoreModule: 98,
    RowGroupingModule: 283,
    RowGroupingOnlyModule: 236,
    RowGroupingPanelModule: 155,
    ServerSideRowModelApiModule: 133,
    ServerSideRowModelCoreModule: 131,
    ServerSideRowModelDefaultModule: 264,
    ServerSideRowModelModule: 610,
    ServerSideRowModelHierarchyModule: 133,
    ServerSideRowModelRowSelectionModule: 131,
    ServerSideRowModelSortModule: 143,
    SetFilterCoreModule: 170,
    SetFilterModule: 177,
    SetFloatingFilterModule: 177,
    SideBarModule: 67,
    SkeletonCellRendererModule: 46,
    SparklinesModule: 47,
    StatusBarCoreModule: 75,
    StatusBarModule: 76,
    StatusBarSelectionModule: 76,
    TreeDataCoreModule: 87,
    TreeDataModule: 120,
    ViewportRowModelCoreModule: 55,
    ViewportRowModelDefaultModule: 194,
    ViewportRowModelModule: 545,
};

export interface ModuleTest {
    modules: ModuleName[];
    expectedSize: number;
}

const allCommunityModules: ModuleTest[] = Object.entries(AllCommunityModules).map(([m, s]) => ({
    modules: [m as ModuleName],
    expectedSize: s,
}));
const allEnterpriseModules: ModuleTest[] = Object.entries(AllEnterpriseModules).map(([m, s]) => ({
    modules: [m as ModuleName],
    expectedSize: s,
}));

const commonFeatureSets: ModuleTest[] = [
    { modules: ['ClientSideRowModelCoreModule', 'SortModule'], expectedSize: 40 },
    { modules: ['ClientSideRowModelCoreModule', 'SortModule', 'FilterModule'], expectedSize: 178 },
];

export const moduleCombinations: ModuleTest[] = [
    { modules: [], expectedSize: 308 },
    ...commonFeatureSets,
    {
        modules: ['AgChartsCommunityModule' as any, 'IntegratedChartsModule'],
        expectedSize: 1200,
    },
    {
        modules: ['AgChartsEnterpriseModule' as any, 'IntegratedChartsModule'],
        expectedSize: 1840,
    },
    {
        modules: ['AgChartsCommunityModule' as any, 'SparklinesModule'],
        expectedSize: 820,
    },
    {
        modules: ['AgChartsEnterpriseModule' as any, 'SparklinesModule'],
        expectedSize: 1452,
    },
    ...allCommunityModules, //.slice(0, 3),
    ...allEnterpriseModules, //.slice(0, 3),
];
